require("bearvim.plugins-setup")
-- core options
require("bearvim.core.options")
require("bearvim.core.keymaps")
require("bearvim.core.colorscheme")
require("bearvim.core.dashboard")
require("bearvim.core.autocommands")

require("bearvim.plugins.general")
require("bearvim.plugins.indentblankline")
require("bearvim.plugins.autopairs")
require("bearvim.plugins.lualine")
require("bearvim.plugins.nvimtree")
require("bearvim.plugins.bufferline")
require("bearvim.plugins.telescope")
require("bearvim.plugins.treesitter")
require("bearvim.plugins.comment")
require("bearvim.plugins.gitsigns")
require("bearvim.plugins.vimwiki")
require("bearvim.plugins.bookmark")
require("bearvim.plugins.session-manager")
require("bearvim.plugins.markdown-preview")
-- require("bearvim.plugins.autosave")
require("bearvim.plugins.vimtasks")
require("bearvim.plugins.vimtex")
require("bearvim.plugins.luasnip")
require("bearvim.plugins.project")
require("bearvim.plugins.lsp")

-- lsp plugins.
-- require("bearvim.plugins.lsp.mason")
-- require("bearvim.plugins.lsp.lspsaga")
-- require("bearvim.plugins.lsp.lspconfig")
-- require("bearvim.plugins.lsp.null-ls")
